server:
  port: 8888
  servlet:
    context-path: /abc
spring:
  datasource:
    hikari:
      max-lifetime: 3000
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      connection-test-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reserved_assistant
    username: root
    password: 123456
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true



#config:
#  jwt:
#    # 加密密钥
#    secret: abcdefg1234567
#    # token有效时长
#    expire: 3600
#    # header 名称
#    header: token

