spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
    # 静态资源访问接口前缀
    static-path-pattern: /static/**
  mail:
    #这个需要根据你开启的服务的邮箱是QQ邮箱,还是网易邮箱区分
    #smtp.163.com为网易邮箱,smtp.qq.com为QQ邮箱
    host: smtp.qq.com
    username: 1356267228@qq.com #你开通SMTP服务的邮箱账号
    password: tinwjjsgmqemhgge #刚刚生成的授权码,不是邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,file:${file.basePath}

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book ---> addressBook
    map-underscore-to-camel-case: true

file:
  basePath: E:\ReservedAssistanceFile
  prefix: http://127.0.0.1:${server.port}${server.servlet.context-path}/static/